
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.au.cc.gallery;

import java.util.Map;
import java.util.HashMap;

import spark.ModelAndView;
import spark.template.handlebars.HandlebarsTemplateEngine;

import static spark.Spark.*;

public class App {
    public String getGreeting() {
        return "Hello LaToya";
    }

    public static void main(String[] args) throws Exception {
        //System.out.println(new App().getGreeting());
	//S3.demo();
	//DB2.demo();
        port(5000);
	get("/hello", (req, res) -> "Hello World");
	get("/hello2", (req, res) -> "<!DOCTYPE html><html><head><title>Hello</title><meta charset=\"utf-8\" /></head><body><h1>Hello World</h1></body></html>");

	get("/goodbye", (req, res) -> "Goodbye");

	get("/greet/:name", (req, res) -> "Nice to meet you "+ req.params("name"));

	new Calculator().addRoutes();
    }
}
